In [1]:
import pandas as pd
file_path = "19-20_PPG_table.csv"
stats = pd.read_csv(file_path, encoding='ISO-8859–1')

In [3]:
stats

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,James Harden,SG,30,HOU,68,68,36.5,9.9,22.3,...,0.865,1.0,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3
1,2,Bradley Beal,SG,26,WAS,57,57,36.0,10.4,22.9,...,0.842,0.9,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5
2,3,Damian Lillard,PG,29,POR,66,66,37.5,9.5,20.4,...,0.888,0.5,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0
3,4,Trae Young,PG,21,ATL,60,60,35.3,9.1,20.8,...,0.860,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6
4,5,Giannis Antetokounmpo,PF,25,MIL,63,63,30.4,10.9,19.7,...,0.633,2.2,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,255,Semi Ojeleye,PF,25,BOS,69,6,14.7,1.2,2.8,...,0.875,0.4,1.7,2.1,0.5,0.3,0.1,0.3,1.2,3.4
255,256,Grant Williams,PF,21,BOS,69,5,15.1,1.3,3.1,...,0.722,0.9,1.7,2.6,1.0,0.4,0.5,0.7,2.4,3.4
256,257,Rodney McGruder,SG,28,LAC,56,4,15.6,1.3,3.2,...,0.559,0.5,2.2,2.7,0.6,0.5,0.1,0.4,1.3,3.3
257,258,Goga Bitadze,C,20,IND,54,2,8.7,1.3,2.8,...,0.727,0.5,1.5,2.0,0.4,0.2,0.7,0.5,1.2,3.2
258,259,Matthew Dellavedova,PG,29,CLE,57,4,14.4,1.1,3.1,...,0.865,0.3,1.0,1.3,3.2,0.4,0.0,1.0,1.4,3.1

In [4]:
name_split = stats["Player"].str.split(" ",n=1,expand=True)
stats["First Name"] = name_split[0]
stats["Last Name"] = name_split[1]
stats.drop(columns=["Player"],inplace=True)

In [5]:
stats

,Rk,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,First Name,Last Name
0,1,SG,30,HOU,68,68,36.5,9.9,22.3,0.444,...,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3,James,Harden
1,2,SG,26,WAS,57,57,36.0,10.4,22.9,0.455,...,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5,Bradley,Beal
2,3,PG,29,POR,66,66,37.5,9.5,20.4,0.463,...,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0,Damian,Lillard
3,4,PG,21,ATL,60,60,35.3,9.1,20.8,0.437,...,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,Trae,Young
4,5,PF,25,MIL,63,63,30.4,10.9,19.7,0.553,...,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5,Giannis,Antetokounmpo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,255,PF,25,BOS,69,6,14.7,1.2,2.8,0.408,...,1.7,2.1,0.5,0.3,0.1,0.3,1.2,3.4,Semi,Ojeleye
255,256,PF,21,BOS,69,5,15.1,1.3,3.1,0.412,...,1.7,2.6,1.0,0.4,0.5,0.7,2.4,3.4,Grant,Williams
256,257,SG,28,LAC,56,4,15.6,1.3,3.2,0.398,...,2.2,2.7,0.6,0.5,0.1,0.4,1.3,3.3,Rodney,McGruder
257,258,C,20,IND,54,2,8.7,1.3,2.8,0.467,...,1.5,2.0,0.4,0.2,0.7,0.5,1.2,3.2,Goga,Bitadze
258,259,PG,29,CLE,57,4,14.4,1.1,3.1,0.354,...,1.0,1.3,3.2,0.4,0.0,1.0,1.4,3.1,Matthew,Dellavedova

In [6]:
stats_df = stats[["Rk","First Name", "Last Name", "Pos","Age","Tm","G","GS","MP","FG","FGA","FG%","3P","3PA","3P%","2P","2PA","2P%","eFG%","FT","FTA","FT%","ORB","DRB","TRB","AST","STL","BLK","TOV","PF","PTS"]]
stats_df.head()

,Rk,First Name,Last Name,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,James,Harden,SG,30,HOU,68,68,36.5,9.9,...,0.865,1.0,5.5,6.6,7.5,1.8,0.9,4.5,3.3,34.3
1,2,Bradley,Beal,SG,26,WAS,57,57,36.0,10.4,...,0.842,0.9,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5
2,3,Damian,Lillard,PG,29,POR,66,66,37.5,9.5,...,0.888,0.5,3.8,4.3,8.0,1.1,0.3,2.9,1.7,30.0
3,4,Trae,Young,PG,21,ATL,60,60,35.3,9.1,...,0.860,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6
4,5,Giannis,Antetokounmpo,PF,25,MIL,63,63,30.4,10.9,...,0.633,2.2,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5